# Generated by Django 3.2.14 on 2022-07-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregistratioin',
            old_name='emai',
            new_name='email',
        ),
    ]
